-- fix_chapter2_guide_explanations.sql
-- Replaces Roman Urdu guide_explanation text with clean English for all Chapter 2 rows.
-- Run in Supabase SQL editor or via psql.

UPDATE content_chunks SET guide_explanation = 'When gas pressure is reduced to 0.1 mmHg and a high voltage is applied, rays emerge from the cathode — these are called cathode rays. Goldstein named them cathode rays in 1886 because they originate from the cathode. J.J. Thomson later proved these are negatively charged particles. G.J. Stoney named them electrons in 1891. Crucially, the same rays are produced regardless of the gas used or the electrode material — proving that cathode rays are composed of universal particles (electrons) present in all matter.' WHERE id = '817037fa-df3f-4b24-b7aa-bbd400c62dc4';

UPDATE content_chunks SET guide_explanation = 'There are 13 important properties of cathode rays: (1) They travel in straight lines. (2) They cast shadows of opaque objects. (3) They produce fluorescence. (4) They heat metals. (5) They can rotate a pin-wheel, proving they have mass and kinetic energy. (6) They produce X-rays when hitting a heavy metal anode. (7) They ionize gases. (8) They cause chemical changes (reducing effect). (9) They penetrate thin metallic sheets of Al and Au. (10) They deflect towards the positive plate in an electric field, proving negative charge. (11) They are deflected by a magnetic field. (12) e/m ratio = 1.7588×10¹¹ C/kg. (13) Charge = 1.6022×10⁻¹⁹ C.' WHERE id = 'd2ef25e9-533e-4c25-ac34-982aecf71ed8';

UPDATE content_chunks SET guide_explanation = 'The mass of the electron is calculated using m = e ÷ (e/m). Thomson measured the e/m ratio (1.7588×10¹¹ C/kg) from cathode ray experiments, while Millikan measured the charge (1.6022×10⁻¹⁹ C) using the oil drop experiment. Substituting both values gives the electron mass as 9.11×10⁻³¹ kg. The electron is 1836 times lighter than the proton.' WHERE id = 'af3493de-1ed9-46f9-b85e-d8bccfa1fa0e';

UPDATE content_chunks SET guide_explanation = 'Goldstein drilled holes (canals) in the cathode of the discharge tube. Cathode rays knocked electrons out of gas molecules, forming positive ions that moved toward the cathode and passed through the holes — these are canal rays. When hydrogen gas is used, the e/m ratio is at its maximum (9.54×10⁷ C/kg), identifying these lightest positive particles as protons. Rutherford suggested the name proton from the Greek word protos meaning first. Canal ray e/m varies with different gases because it depends on the mass of the gas ion, unlike cathode rays which always give the same e/m.' WHERE id = '52d39480-4cd4-4a63-9679-db46c61ff454';

UPDATE content_chunks SET guide_explanation = 'Scientists noticed that the total mass of electrons and protons in an atom was always less than the actual atomic mass, suggesting another heavy neutral particle must exist. Rutherford predicted this particle in 1920. In 1932, James Chadwick confirmed its existence by bombarding Beryllium with alpha particles from Polonium, producing highly penetrating neutral particles called neutrons. Because the neutron carries no charge, it is not deflected by electric or magnetic fields. Chadwick received the Nobel Prize for this discovery.' WHERE id = 'c03aa040-1e8b-4366-ac27-85be5c3fdaa0';

UPDATE content_chunks SET guide_explanation = 'The three fundamental subatomic particles are: Electron — mass 9.11×10⁻³¹ kg (0.00055 amu), charge −1. Proton — mass 1.67×10⁻²⁷ kg (1.0073 amu), charge +1. Neutron — mass 1.67×10⁻²⁷ kg (1.0087 amu), charge 0. The proton and neutron reside in the nucleus; electrons revolve around it. The proton is 1836 times heavier than the electron, and the neutron is 1842 times heavier. The arrangement of these three particles determines all physical and chemical properties of an atom.' WHERE id = '0e5492d8-f60b-4331-b7a9-e6e36a8e3a98';

UPDATE content_chunks SET guide_explanation = 'Bohr proposed his atomic model in 1913 to correct the defects of Rutherford''s model, basing it on Planck''s quantum theory. The seven postulates are: (1) electrons revolve in fixed circular orbits (shells) around the nucleus; (2) each orbit has a fixed energy that increases with distance from the nucleus; (3) an electron in a fixed orbit does not emit or absorb energy; (4) an electron gaining energy jumps to a higher orbit; (5) an electron losing energy falls to a lower orbit and emits radiation ΔE = hν = E₂ − E₁; (6) energy is emitted or absorbed only as discrete quanta; (7) angular momentum is quantized: mvr = nh/2π, where n is the shell number and h = 6.626×10⁻³⁴ J·s.' WHERE id = '7ed173ff-f2a4-4fee-be1e-1fbf0fb0f5cf';

UPDATE content_chunks SET guide_explanation = 'The derivation follows these steps: (1) Coulombic force of attraction = Ze²/4πε₀r². (2) Centrifugal force = mv²/r. (3) For a stable orbit, these forces balance: mv²/r = Ze²/4πε₀r², giving mv² = Ze²/4πε₀r. (4) From angular momentum quantization mvr = nh/2π, we get v² = n²h²/4π²m²r². (5) Combining both equations and solving: rₙ = n² × (ε₀h²/Ze²πm). (6) For hydrogen (Z=1): rₙ = n² × 0.529 Å. Key rule for calculations: radius is proportional to n² — if the orbit number doubles, the radius becomes four times larger.' WHERE id = '7a1f2e77-836c-4012-90ae-e4db9e2938c9';

UPDATE content_chunks SET guide_explanation = 'Total energy of the electron equals kinetic energy (KE) plus potential energy (PE). KE = Ze²/8πε₀r is positive (motion energy); PE = −Ze²/4πε₀r is negative (attraction to nucleus). The negative sign indicates the electron is bound — it would need energy input to escape. Energy becomes less negative (increases) as n increases, meaning higher shells are less tightly bound. The ground state is n=1 (most negative energy). For hydrogen: Eₙ = −1313/n² kJ/mol. Key values: E₁=−1313, E₂=−328, E₃=−146, E₄=−82 kJ/mol.' WHERE id = 'e93c3739-92d4-4cc7-a06e-8f13d6643530';

UPDATE content_chunks SET guide_explanation = 'The energy difference between two orbits is: ΔE = 1313(1/n₁² − 1/n₂²) kJ/mol, where n₁ is the lower orbit and n₂ is the higher orbit. When an electron moves upward (n₁ → n₂), energy is absorbed and ΔE is positive. When it falls downward (n₂ → n₁), energy is emitted. For atomic units, use ΔE = 2.18×10⁻¹⁸(1/n₁² − 1/n₂²) J/atom. Exam tip: Lyman series transitions (n₁=1) produce the largest energy differences because n₁=1 gives the smallest denominator in the formula.' WHERE id = 'b00b5c68-c762-4dde-a0ee-0cbeeb9af914';

UPDATE content_chunks SET guide_explanation = 'When an electron changes orbit, the frequency of emitted radiation is given by ν = ΔE/h. Wave number (ν̄) is the number of waves per unit length — it equals the reciprocal of wavelength: ν̄ = 1/λ. The Rydberg constant R = 1.097×10⁷ m⁻¹ appears in the combined formula: ν̄ = R(1/n₁² − 1/n₂²) m⁻¹. Wavelength follows from: λ = 1/ν̄. All key relationships are: c = νλ, ν = c/λ, ν̄ = 1/λ, ν = cν̄, where c = 3×10⁸ m/s.' WHERE id = 'ce2b1c2a-748d-41f3-8dbe-d03498bcd9df';

UPDATE content_chunks SET guide_explanation = 'There are two types of spectra. A continuous spectrum has no gaps between colors — like a rainbow — with no clear boundary between one color and the next. A line spectrum (also called atomic spectrum) shows distinct colored lines separated by dark spaces. Line spectra come in two forms: emission spectrum shows bright lines on a dark background, produced when an element is heated and its atoms emit specific wavelengths; absorption spectrum shows dark lines on a bright background, produced when white light passes through a cooled substance whose atoms absorb specific wavelengths. An important fact: emission and absorption lines of the same element appear at exactly the same wavelength positions.' WHERE id = 'aa1a6562-2a52-4f56-8b5b-41fa48f9f7e0';

UPDATE content_chunks SET guide_explanation = 'The hydrogen spectrum has five series. Lyman series (UV region): electron returns to n₁=1. Balmer series (Visible region): electron returns to n₁=2 — J.J. Balmer discovered these four visible lines in 1884. Paschen series (Near IR): n₁=3. Brackett series (Mid IR): n₁=4. Pfund series (Far IR): n₁=5. Memory tip: L–B–P–Br–Pf (Lyman–Balmer–Paschen–Brackett–Pfund). In every series, n₂ is always greater than n₁. The series name identifies which orbit the electron finally falls to; a transition from any higher orbit to n₁ produces a line in that series.' WHERE id = 'f08a5a0f-dbd9-4106-ae31-39d3ac63975c';

UPDATE content_chunks SET guide_explanation = 'Bohr''s model works only for hydrogen and hydrogen-like ions (He⁺, Li²⁺, Be³⁺) — it cannot explain spectra of multi-electron atoms because it ignores electron-electron repulsions. Under high-resolution spectrometers, each spectral line shows fine structure (multiple closely spaced lines) that the model cannot account for. It also fails to explain the Zeeman effect (splitting of spectral lines in a magnetic field) and the Stark effect (splitting in an electric field). Modern quantum mechanics shows that electrons do not travel in well-defined fixed circular orbits. Additionally, the model provides no explanation for chemical bond formation.' WHERE id = 'c14e0331-e13e-4d38-b45a-bac9a5d7180c';

UPDATE content_chunks SET guide_explanation = 'Max Planck proposed this theory in 1900. Energy is not emitted or absorbed continuously; instead it is released in discrete packets called quanta (singular: quantum). The quantum of light energy is called a photon. The energy of one quantum is given by Planck''s equation: E = hν, where h = 6.626×10⁻³⁴ J·s (Planck''s constant) and ν is the frequency of radiation. A body can only emit or absorb energy in whole-number multiples of hν: E = nhν (n = 1, 2, 3...). This means energy is quantized — it can take only specific values (hν, 2hν, 3hν...) and not arbitrary values.' WHERE id = '69b870dd-453f-4cd1-829d-1e1b1f4fc478';

UPDATE content_chunks SET guide_explanation = 'Wavelength (λ) is the distance between two adjacent crests or troughs, measured in Angstrom (Å = 10⁻¹⁰ m) or nanometers (nm = 10⁻⁹ m). Frequency (ν) is the number of wave cycles passing a fixed point per second, measured in Hz; frequency and wavelength are inversely related: ν = c/λ. The speed of light c = 3×10⁸ m/s is constant for all electromagnetic radiation. Wave number (ν̄) is the number of waves per unit length = 1/λ, measured in m⁻¹ or cm⁻¹. All energy-radiation relationships: E = hν = hc/λ = hcν̄.' WHERE id = '2c2cea9e-71d8-43b6-9189-249f8b96d53e';

UPDATE content_chunks SET guide_explanation = 'Start with Planck''s equation: E = hν. Use the relationship between frequency and wavelength: ν = c/λ. Substitute into the energy equation: E = h × (c/λ) = hc/λ. Since wave number is defined as ν̄ = 1/λ, substitute to get: E = hcν̄. Proof complete. This derivation is frequently examined in both ETEA and BISE papers — learn each step clearly.' WHERE id = '829f062a-d8cb-4c96-9510-44e6e83ae2a1';

UPDATE content_chunks SET guide_explanation = 'X-rays were accidentally discovered by W.C. Roentgen in 1895 while studying cathode rays. They are produced when high-speed electrons (cathode rays) strike a heavy metal anode — the sudden deceleration of electrons at the anode releases energy as X-ray photons. The cathode is concave-shaped to focus electrons on a small spot of the anode. Key properties: they are electrically neutral, so they are not deflected by electric or magnetic fields; they ionize gases; they cause fluorescence in NaCl and uranium; they blacken photographic plates; they diffract through crystalline substances; their penetrating power varies with the material. Applications include: diagnosing bone fractures (medicine), crystal structure analysis (XRD), and determining the DNA double helix structure (Watson and Crick).' WHERE id = '8cf7fc7a-2dc6-4e26-8b84-20ea1769fa8a';

UPDATE content_chunks SET guide_explanation = 'Moseley used 38 different elements as X-ray tube targets and observed that higher atomic number elements produced higher frequency X-rays. Moseley''s Law states: the square root of the X-ray frequency (√ν) is directly proportional to the atomic number (Z) of the element: √ν = a(Z − b). For the K-series, the screening constant b = 1; a is a proportionality constant that depends on the spectral series. This equation allows calculation of atomic number from measured X-ray frequencies. Most significantly, Moseley''s Law proved that the atomic number (number of protons in the nucleus) — not atomic mass — is the true fundamental property that determines an element''s identity.' WHERE id = '5118682b-f113-467e-b508-330777f779a1';

UPDATE content_chunks SET guide_explanation = 'Quantum numbers are a set of numerical values that give complete information about the energy, shape, orientation, and spin state of an electron in an atom — they are often called the address of electrons. There are four quantum numbers: n (principal), l (azimuthal), m (magnetic), and s (spin). The first three are derived mathematically from solutions to Schrödinger''s wave equation; spin was discovered independently. Together, the four quantum numbers uniquely identify every electron in an atom — just as a postal address (country, city, street, house number) uniquely identifies a location.' WHERE id = 'a31d427d-7496-4d13-bdad-af72fb59d9fd';

UPDATE content_chunks SET guide_explanation = 'The principal quantum number n identifies which main shell (energy level) an electron occupies. Values are n = 1, 2, 3, 4... corresponding to shells K, L, M, N. As n increases, the electron is farther from the nucleus and has higher energy. The maximum number of electrons a shell can hold = 2n²: K(n=1) holds 2, L(n=2) holds 8, M(n=3) holds 18, N(n=4) holds 32. At n=1 (ground state), the electron is most tightly bound to the nucleus and has the lowest energy.' WHERE id = 'e06375c7-5e54-4fdb-92f1-91a7a9cf720d';

UPDATE content_chunks SET guide_explanation = 'The azimuthal quantum number l identifies the sub-shell and describes the shape of the orbital. Values run from l = 0 to (n−1): l=0 is the s sub-shell (spherical shape), l=1 is the p sub-shell (dumbbell shape), l=2 is the d sub-shell (double dumbbell), l=3 is the f sub-shell (complex shape). The letters stand for sharp, principal, diffused, and fundamental. Maximum electrons in a sub-shell = 2(2l+1), giving s=2, p=6, d=10, f=14 electrons. The total number of sub-shells in a given shell equals the value of n.' WHERE id = '83fde127-e7a3-40ea-b473-970b7d4d13bb';

UPDATE content_chunks SET guide_explanation = 'The magnetic quantum number m arises from the Zeeman effect — the observed splitting of spectral lines in a magnetic field. It describes the number of orbitals in a sub-shell and their spatial orientation. Values of m range from −l to +l, giving a total of (2l+1) values: the s sub-shell (l=0) has 1 orbital (m=0); the p sub-shell (l=1) has 3 orbitals: px (m=−1), py (m=0), pz (m=+1); the d sub-shell has 5 orbitals; the f sub-shell has 7 orbitals. The total number of orbitals in any shell = n².' WHERE id = 'd2c0ed46-2879-40c6-aeee-ae2eb924bb94';

UPDATE content_chunks SET guide_explanation = 'The spin quantum number describes the direction of an electron''s rotation on its own axis. It has only two possible values: +½ (clockwise spin, shown as ↑) or −½ (anticlockwise spin, shown as ↓). A maximum of 2 electrons can occupy one orbital, and they must have opposite spins (↑↓) — these are called paired electrons. Electrons in separate orbitals with the same spin direction are called parallel (↑↑ or ↓↓). The Stern-Gerlach experiment provided evidence for spin: a beam of hydrogen atoms split into two parts in a magnetic field, corresponding to ms = +½ and ms = −½.' WHERE id = '959c1ece-eeee-43a9-9c66-09f313e8e6c2';

UPDATE content_chunks SET guide_explanation = 'An orbital is the three-dimensional region around the nucleus where the probability of finding an electron is maximum — it has no strict outer boundary. The s-orbital (l=0) is spherical in shape and lies closest to the nucleus; size increases as 1s < 2s < 3s. The p-orbitals (l=1) are dumbbell-shaped, each with two lobes; the three p-orbitals (px, py, pz) are oriented along the x, y, and z axes and are perpendicular to each other. The five d-orbitals have more complex shapes: dxy, dyz, and dxz have lobes directed between the respective axes, while dz² resembles a p-orbital with an additional ring (torus) around its center. A nodal surface is the region where electron probability equals zero.' WHERE id = '5e77de39-f8cb-4b59-a059-95c1c16e1ad9';

UPDATE content_chunks SET guide_explanation = 'Electronic configuration describes how electrons are distributed among the sub-shells and orbitals of an atom. Three rules govern the filling: Aufbau Principle, Pauli Exclusion Principle, and Hund''s Rule. The n+l rule determines the energy sequence. Notation uses: principal shell number + sub-shell letter + superscript (number of electrons) — for example, 1s² means 2 electrons in the 1s sub-shell. The standard filling order is: 1s → 2s → 2p → 3s → 3p → 4s → 3d → 4p → 5s → 4d → 5p → 6s → 4f → 5d → 6p → 7s...' WHERE id = '350fa588-fac6-4847-8f0c-55863547a475';

UPDATE content_chunks SET guide_explanation = 'Aufbau is a German word meaning building up. The principle states that electrons fill orbitals in order of increasing energy, starting from the lowest energy orbital first. The n+l rule determines energy order: the orbital with the lower (n+l) value has lower energy and is filled first. When two orbitals have the same n+l value, the one with the lower n is filled first. Example: for 4s, n+l = 4+0 = 4; for 3d, n+l = 3+2 = 5 — so 4s fills before 3d. This is why Potassium (Z=19) has configuration [Ar]4s¹ and Calcium (Z=20) has [Ar]4s², not [Ar]3d¹ or [Ar]3d².' WHERE id = '3a70b4a5-527b-446c-a37b-325b433e6085';

UPDATE content_chunks SET guide_explanation = 'Proposed by Wolfgang Pauli in 1925, the principle states: no two electrons in the same atom can have an identical set of all four quantum numbers (n, l, m, s). In any one orbital, the values of n, l, and m are already fixed and the same for both electrons — the only quantum number that can differ is spin (s). Since s has only two values (+½ and −½), a maximum of 2 electrons can occupy one orbital, and they must have opposite spins (↑↓, called paired electrons). Example for Helium 1s²: first electron n=1, l=0, m=0, s=+½; second electron n=1, l=0, m=0, s=−½.' WHERE id = 'b484ee98-5af1-4ce7-b16f-cc73f9ecce12';

UPDATE content_chunks SET guide_explanation = 'Named after F.H. Hund, the rule states: when degenerate orbitals (orbitals of equal energy) are available, electrons fill them singly first — each with the same spin direction (parallel spins ↑↑) — before any pairing begins. The most stable arrangement has the maximum number of unpaired electrons with parallel spins. For Carbon (Z=6): 1s²2s²2p² — both 2p electrons go into separate 2px and 2py orbitals as (↑)(↑)( ), not paired in one orbital. For Nitrogen (Z=7): 1s²2s²2p³ — all three 2p electrons are (↑)(↑)(↑). For Oxygen (Z=8): 1s²2s²2p⁴ — one 2p orbital becomes paired (↑↓) while two remain singly occupied (↑)(↑).' WHERE id = '8c4521ee-875c-4035-96e5-7f1e4b72ff46';

UPDATE content_chunks SET guide_explanation = 'Use noble gas notation to write configurations concisely ([He], [Ne], [Ar], [Kr]). Two critical exceptions to memorize: Chromium (Z=24): expected [Ar]4s²3d⁴, actual [Ar]4s¹3d⁵ — because a half-filled d sub-shell (3d⁵) is extra stable due to symmetrical distribution and maximum exchange energy. Copper (Z=29): expected [Ar]4s²3d⁹, actual [Ar]4s¹3d¹⁰ — because a completely filled d sub-shell (3d¹⁰) provides maximum exchange energy stability. Also note: Potassium (Z=19) = [Ar]4s¹ because Aufbau principle places 4s (n+l=4) before 3d (n+l=5) in the filling order.' WHERE id = '44ed84ab-4e99-4f75-a470-62bd7dd45eaa';

UPDATE content_chunks SET guide_explanation = 'An orbit (Bohr''s model) is a well-defined, fixed circular path in which an electron revolves around the nucleus; it can hold up to 2n² electrons and its shape is always circular. An orbital (quantum mechanics) is the three-dimensional space around the nucleus where the probability of finding an electron is maximum; each orbital holds at most 2 electrons with opposite spins and has no strict outer boundary. Orbital shapes vary: s is spherical, p is dumbbell-shaped, d is complex. Orbits contradict the Heisenberg Uncertainty Principle because they imply a simultaneously known exact position and momentum; orbitals are fully consistent with it.' WHERE id = 'cc397a2d-9548-495e-83af-13d86cb04096';

UPDATE content_chunks SET guide_explanation = 'This is a complete formula reference for Chapter 2 numerical problems. Radius: rₙ = n² × 0.529 Å (hydrogen). Energy: Eₙ = −1313/n² kJ/mol (hydrogen). Energy difference: ΔE = 1313(1/n₁² − 1/n₂²) kJ/mol. Wave number: ν̄ = 1.097×10⁷(1/n₁² − 1/n₂²) m⁻¹. Frequency: ν = c × ν̄. Wavelength: λ = 1/ν̄. Photon energy: E = hν = hc/λ = hcν̄. Shell capacity: 2n². Sub-shell capacity: 2(2l+1). Orbitals per sub-shell: 2l+1. Total orbitals in shell: n². Moseley''s Law: √ν = a(Z−b), K-series b=1. Constants: h = 6.626×10⁻³⁴ J·s, c = 3×10⁸ m/s, R = 1.097×10⁷ m⁻¹, e = 1.6022×10⁻¹⁹ C.' WHERE id = 'c122a86f-e3e7-4c93-ad3f-1f80083efd06';
