import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service – VoiceUstad',
  description: 'The terms that govern your use of VoiceUstad.',
}

const LAST_UPDATED = 'July 16, 2026'

const section: React.CSSProperties = {
  background: '#111d30',
  border: '1px solid rgba(255,255,255,0.08)',
  borderRadius: '16px',
  padding: '24px 26px',
  marginBottom: '16px',
}
const h2: React.CSSProperties = {
  fontSize: '16px', fontWeight: 700, color: 'white', margin: '0 0 10px',
}
const p: React.CSSProperties = {
  fontSize: '14px', color: '#94a3b8', lineHeight: 1.75, margin: '0 0 10px',
}
const li: React.CSSProperties = {
  fontSize: '14px', color: '#94a3b8', lineHeight: 1.75, marginBottom: '6px',
}

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100vh',
      background: '#07101f',
      color: '#e2e8f0',
      fontFamily: 'var(--font-dm, DM Sans, sans-serif)',
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', gap: '12px',
        padding: '16px 24px', borderBottom: '1px solid #1a2d47',
      }}>
        <a href="/" style={{ color: '#f59e0b', textDecoration: 'none', fontWeight: 800, fontSize: '15px' }}>
          🎙️ VoiceUstad
        </a>
        <span style={{ color: '#334155' }}>/</span>
        <span style={{ fontWeight: 700, fontSize: '15px' }}>Terms of Service</span>
      </div>

      <div style={{ maxWidth: '680px', margin: '0 auto', padding: '32px 20px 80px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 800, color: 'white', margin: '0 0 6px' }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: '12.5px', color: '#64748b', margin: '0 0 28px' }}>
          Last updated: {LAST_UPDATED}
        </p>

        <div style={section}>
          <h2 style={h2}>1. The service</h2>
          <p style={p}>
            VoiceUstad is an AI-powered educational platform for FSc and MDCAT students in Pakistan.
            It provides chemistry explanations in English text with Urdu voice audio, topic summaries,
            quizzes, and progress tracking, aligned with the KPK Board curriculum. By creating an
            account or using VoiceUstad, you agree to these terms.
          </p>
        </div>

        <div style={section}>
          <h2 style={h2}>2. Subscription &amp; payment</h2>
          <ul style={{ margin: 0, paddingLeft: '20px' }}>
            <li style={li}>New accounts receive a <strong style={{ color: '#e2e8f0' }}>free trial</strong>; after it ends, continued access requires a subscription of <strong style={{ color: '#e2e8f0' }}>Rs. 499 per month</strong>.</li>
            <li style={li}>Payment is made manually via <strong style={{ color: '#e2e8f0' }}>EasyPaisa or JazzCash</strong> to the account details shown on our pricing page.</li>
            <li style={li}>After paying, you send a payment screenshot to our <strong style={{ color: '#e2e8f0' }}>WhatsApp confirmation number</strong> (shown on the pricing page). Your access is activated manually after verification, normally within a few hours.</li>
            <li style={li}>Subscriptions are for a single account and are activated for the period paid; there is no auto-renewal — you pay again each month to continue.</li>
          </ul>
        </div>

        <div style={section}>
          <h2 style={h2}>3. Your responsibilities</h2>
          <ul style={{ margin: 0, paddingLeft: '20px' }}>
            <li style={li}>Provide accurate account information (including your class and board, which personalize your content).</li>
            <li style={li}>Keep your account credentials private and do not share your account with others — one subscription covers one student.</li>
            <li style={li}>Use VoiceUstad appropriately: for studying. Do not attempt to abuse, overload, disrupt, or reverse-engineer the service, and do not use it for anything unlawful.</li>
          </ul>
        </div>

        <div style={section}>
          <h2 style={h2}>4. Content &amp; educational disclaimer</h2>
          <p style={p}>
            VoiceUstad&apos;s explanations are grounded in KPK Board textbooks, and quizzes follow the
            board syllabus. However, answers and Urdu voice explanations are generated by AI and{' '}
            <strong style={{ color: '#e2e8f0' }}>may contain errors or inaccuracies</strong>. VoiceUstad
            is a study aid — it is <strong style={{ color: '#e2e8f0' }}>not a replacement for your
            official textbooks, your teachers, or your own preparation</strong>. Always verify important
            facts against your textbook before an exam.
          </p>
          <p style={p}>
            The VoiceUstad name, app, and original content are owned by us. Textbook material referenced
            in explanations belongs to its respective publishers/boards. You may use content from the
            app for your personal study only, not for redistribution or resale.
          </p>
        </div>

        <div style={section}>
          <h2 style={h2}>5. Limitation of liability</h2>
          <p style={p}>
            VoiceUstad is provided &quot;as is&quot;. To the maximum extent permitted by law, we are not
            liable for any indirect or consequential damages arising from your use of the service —
            including exam outcomes, reliance on AI-generated content, or temporary unavailability of
            the app. Our total liability for any claim is limited to the amount you paid for the
            subscription month in which the claim arose.
          </p>
        </div>

        <div style={section}>
          <h2 style={h2}>6. Termination &amp; refunds</h2>
          <p style={p}>
            You may stop using VoiceUstad at any time and may request account deletion (see our{' '}
            <a href="/privacy" style={{ color: '#f59e0b', textDecoration: 'none', fontWeight: 600 }}>Privacy Policy</a>).
            We may suspend or terminate accounts that violate these terms (for example, account sharing
            or abuse of the service).
          </p>
          <p style={p}>
            <strong style={{ color: '#e2e8f0' }}>All payments are final — subscription payments are
            non-refundable</strong>, including for partial months or unused time. Please use the free
            trial to decide whether VoiceUstad is right for you before subscribing.
          </p>
        </div>

        <div style={section}>
          <h2 style={h2}>7. Changes to these terms</h2>
          <p style={p}>
            We may update these terms as the service evolves. The &quot;Last updated&quot; date above
            reflects the current version; continued use of VoiceUstad after changes means you accept
            the updated terms.
          </p>
        </div>

        <div style={section}>
          <h2 style={h2}>8. Contact</h2>
          <p style={p}>
            Questions about these terms? Contact us at{' '}
            <a href="mailto:shehzadahmadofficial@gmail.com" style={{ color: '#f59e0b', textDecoration: 'none', fontWeight: 600 }}>
              shehzadahmadofficial@gmail.com
            </a>.
          </p>
        </div>

        <p style={{ fontSize: '12px', color: '#64748b', textAlign: 'center', marginTop: '28px' }}>
          <a href="/privacy" style={{ color: '#64748b' }}>Privacy Policy</a>
          {' · '}
          <a href="/" style={{ color: '#64748b' }}>Back to VoiceUstad</a>
        </p>
      </div>
    </div>
  )
}
